### ISSUE TITLE
Problem when running composer update

### ISSUE THREAD

**Issue by kpirbhai** [qcubed/plugin_bootstrap#35]
When the vendor folder doesn't exist and I run composer update on my project I'm getting the following error:

![image](https://cloud.githubusercontent.com/assets/5413608/17775252/03115ed2-651d-11e6-96b6-8fe2da8609c0.png)

This is happening every time.

Here is my composer.json file:

[composer.txt](https://github.com/qcubed/plugin_bootstrap/files/425013/composer.txt)

I've tried putting twbs before the plugin and after....but I don't think that's the problem. It seems to be something in the composer install script but I am not familiar enough with composer stuff to figure it out.

**Comment by spekary** [comment]
You have to follow the autoload chain all the way until you get to the file in question. Each part needs to be there.

Autoload starts in prepend.inc on line 58 here:
```
        if (file_exists (__QCUBED_CORE__ . '/../../../autoload.php')) {
            require __QCUBED_CORE__ . '/../../../autoload.php'; // Add the Composer autoloader if using Composer
        }

        // Register the autoloader, making sure we go BEFORE the composer autoloader
        spl_autoload_register(array('QApplication', 'Autoload'), true, true);
```

That creates 2 autoloaders, one for composer, and one for QCubed.

The composer autoloader is looking for the autoload.php file in the vendor directory. We could change that to using a define if needed for configuration of other setups, since it assumes that qcubed exists in the vendor directory. But the QCubed plugins all assume they are loaded by composer and using that autoloader.

QApplicationBase::AutoLoad also has an autoloader that looks for QCubed\Plugin type files, but I am pretty sure the problem is the autoload.php file. If it can't find that file, and all the related files in the /vendor/compser directory, it will not find the file you are getting an error about.

**Comment by kpirbhai** [comment]
I forgot to mention that the whole problem is caused because in my project/includes/controls/QControl.class.php I'm extending QCubed\Plugin\Bootstrap\Control

When I change that to extend from QControlBase again it works fine. I can run composer update and then go change it back.

The reason this is an issue is because I'm going to be deploying this project to the server using git hooks to automatically pull the project from the repository and then run composer update on the server to keep everything in sync.

I'm going to see if I can come up with a script for myself that will change the QControl file to extend QControlBase before composer update and then change it back after....but was hoping that there was going to be something could be done with the plugin package itself.

**Comment by spekary** [comment]
So your process involves deleting the vendor directory, and then doing a composer update? That is definitely not an expected usage scenario. Some part of the process is trying to load up QCubed, and since all the parts aren't there, its failing. If you are auto-loading QCubed through a .htaccess file or some other mechanism that automatically loads the qcubed.inc.php file or prepend.inc.php file, that could be the problem.
